version: '3'
services:

  db:
    container_name: typrout-db
    restart: always
    image: postgres:9.6-alpine
    networks:
      - internal_network
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    container_name: typrout-redis
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  es:
    container_name: typrout-es
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal_network
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    container_name: typrout-web
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    environment:
      VIRTUAL_HOST: typrout.ml
      VIRTUAL_PORT: 3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks:
      - internal_network
      - nginx-proxy
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  streaming:
    container_name: typrout-streaming
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    environment:
      VIRTUAL_HOST: streaming.typrout.ml
      VIRTUAL_PORT: 4000
    command: yarn start
    networks:
      - internal_network
      - nginx-proxy
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    container_name: typrout-sidekiq
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    networks:
      - internal_network
    volumes:
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

networks:
  nginx-proxy:
    external: true
  internal_network:
    internal: true
