version: '3'
services:

  db:
    container_name: typrout-db
    restart: always
    image: postgres:9.6-alpine
    networks:
      - internal_network
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    container_name: typrout-redis
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  es:
    container_name: typrout-es
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal_network
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    container_name: typrout-web
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    environment:
      VIRTUAL_HOST: typrout.ml
      VIRTUAL_PORT: 3000
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - internal_network
      - nginx-proxy
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    container_name: typrout-streaming
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    environment:
      VIRTUAL_HOST: streaming.typrout.ml
      VIRTUAL_PORT: 4000
    command: yarn start
    networks:
      - internal_network
      - nginx-proxy
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    container_name: typrout-sidekiq
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - internal_network
      - nginx-proxy
    volumes:
      - ./public/system:/mastodon/public/system
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    build: https://github.com/usbsnowcrash/docker-tor.git
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    build: https://github.com/usbsnowcrash/docker-privoxy.git
#    command: /opt/sbin/privoxy --no-daemon --user privoxy.privoxy /opt/config
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  nginx-proxy:
    external: true
  internal_network:
    internal: true
